# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fetch Reward Lists' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fetch Reward Lists
pod 'Alamofire', '~> 4.8.1' 
pod 'OpenSans'
pod 'NVActivityIndicatorView'

  target 'Fetch Reward ListsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fetch Reward ListsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
